version: '3.8'

services:
  orion-server:
    build:
      context: ./orion-server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - orion-network
    environment:
      - CROWDSEC_URL=http://crowdsec:8080
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      - orion-agent1
      - orion-agent2
      - logstash
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  orion-agent1:
    build:
      context: ./orion-agent
      dockerfile: Dockerfile
    networks:
      - orion-network
    environment:

    expose:
      - "4040"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  agean_cyber:
    build:
      context: ./agean_cyber
      dockerfile: Dockerfile
    networks:
      - orion-network
    environment:
      - AGENT_ID=2
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}  # API keys loaded from the environment
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    expose:
     - "4040"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      volumes:
        - esdata:/usr/share/elasticsearch/data
      networks:
        - orion-network
      ports:
        - "9200:9200"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
      volumes:
        esdata:
          driver: local
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - orion-network
    ports:
      - "5044:5044"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - orion-network
    depends_on:
      - elasticsearch
  
  networks:
  orion-network:
    driver: bridge
